<html xtrf="file:/C:/Users/x/Desktop/adam-gutowski/my_first_map.ditamap" lang="en"><head><meta charset="UTF-8"></meta><meta name="copyright" content="(C) Copyright 2022"></meta><meta name="DC.rights.owner" content="(C) Copyright 2022"></meta>
<link rel="stylesheet" type="text/css" href="file:/C:/Program Files/Oxygen XML Editor 24/frameworks/dita/DITA-OT3.x/plugins/com.oxygenxml.webhelp.responsive/oxygen-webhelp/app/topic-page-print.css"></link>
<link rel="stylesheet" type="text/css" href="file:/C:/Program Files/Oxygen XML Editor 24/frameworks/dita/DITA-OT3.x/plugins/com.oxygenxml.pdf.css/css/print/p-dita.css"></link>
<link rel="stylesheet" type="text/css" href="file:/C:/Program Files/Oxygen XML Editor 24/frameworks/dita/DITA-OT3.x/plugins/com.oxygenxml.editlink/pdf-css.css"></link>
<meta name="generator" content="DITA-OT"></meta><meta name="DC.type" content="map"></meta><meta name="DC.format" content="HTML5"></meta><meta name="DC.language" content="en"></meta><title>my first map</title></head><body class="wh_topic_page"><div class="wh_content_area"><div class="wh_topic_body"><div class="wh_topic_content"><div xmlns:ditaarch="http://dita.oasis-open.org/architecture/2005/" cascade="merge" class="- map/map map" ditaarch:DITAArchVersion="1.3" domains="(map mapgroup-d) (topic abbrev-d) (topic delay-d) a(props deliveryTarget) (map ditavalref-d) (map glossref-d) (topic hazard-d) (topic hi-d) (topic indexing-d) (topic markup-d) (topic pr-d) (topic relmgmt-d) (topic sw-d) (topic ui-d) (topic ut-d) (topic markup-d xml-d)" specializations="@props/deliveryTarget" xml:lang="en" lang="en"><div class="- front-page/front-page front-page"><div class="- front-page/front-page-title front-page-title"><div class="- topic/title title">my first map</div></div></div><div class="- toc/toc toc"><div empty="true" class="- toc/title title"></div>
    <div class="- topic/title title">my first map</div>
    <div is-chapter="true" href="#unique_1" type="concept" class="- map/topicref topicref"><div data-topic-id="myfirstconcept" class="- map/topicmeta topicmeta"><div appid="myfirstconcept" oxy-source="topic" class="- topic/resourceid resourceid"></div><div href="#unique_1" class="- topic/navtitle navtitle">MyFirstConcept</div><div class="- map/shortdesc shortdesc">Description</div></div></div>
    <div is-chapter="true" href="#unique_3" type="reference" class="- map/topicref topicref"><div data-topic-id="r_reference" class="- map/topicmeta topicmeta"><div appid="r_reference" oxy-source="topic" class="- topic/resourceid resourceid"></div><div href="#unique_3" class="- topic/navtitle navtitle">Reference</div><div class="- map/shortdesc shortdesc"></div></div></div>
    <div is-chapter="true" href="#unique_2" type="task" class="- map/topicref topicref"><div data-topic-id="t_new_task" class="- map/topicmeta topicmeta"><div appid="t_new_task" oxy-source="topic" class="- topic/resourceid resourceid"></div><div href="#unique_2" class="- topic/navtitle navtitle">New Task</div><div class="- map/shortdesc shortdesc">12345</div></div></div>
    
</div><article xmlns:nd="http://www.oxygenxml.com/css2fo/named-destinations" class="- topic/topic concept/concept topic concept nested0" aria-labelledby="ariaid-title1" break-before="true" is-chapter="true" id="unique_1" topicrefclass="- map/topicref " nd:nd-id="myfirstconcept" oid="myfirstconcept" specializations="@props/deliveryTarget">
    <h1 class="- topic/title title topictitle1" id="ariaid-title1"><span class="- topic/ph topic/title-wrapper ph title-wrapper">MyFirstConcept</span></h1>
    
    <div class="- topic/body concept/conbody body conbody"><p class="- topic/shortdesc shortdesc">Description</p>
        <p class="- topic/p p"> Test </p>
        <div class="- topic/p p"><pre class="+ topic/pre pr-d/codeblock pre codeblock" id="unique_1_Connect_42_codeblock_ovk_jpz_vsb" nd:nd-id="codeblock_ovk_jpz_vsb" xml:space="preserve"><code>r</code></pre><code class="+ topic/ph pr-d/codeph ph codeph">
                </code>
        </div>
        <p class="- topic/p p"> s </p>
    </div>
<div class="wh_related_links"><nav role="navigation" class="- topic/related-links related-links"><div class="- topic/linklist linklist relref" outputclass="relref" xml:lang="en"><strong>Related reference</strong><ul class="linklist"><li class="linklist"><a class="- topic/link link" format="dita" href="#unique_3" mapclass="- map/topicref " role="friend" scope="local" type="reference">Reference</a></li></ul></div><div class="- topic/linklist linklist relinfo" outputclass="relinfo" xml:lang="en"><strong>Related information</strong><ul class="linklist"><li class="linklist"><a class="- topic/link link" format="dita" href="#unique_2" mapclass="- map/topicref " role="friend" scope="local" type="task" title="12345">New Task</a></li></ul></div></nav></div></article><article xmlns:nd="http://www.oxygenxml.com/css2fo/named-destinations" class="- topic/topic reference/reference topic reference nested0" aria-labelledby="unique_3__unique_3_Connect_42_title_axh_rzg_wsb" break-before="true" is-chapter="true" id="unique_3" topicrefclass="- map/topicref " nd:nd-id="r_reference" oid="r_reference" specializations="@props/deliveryTarget">
    <h1 class="- topic/title title topictitle1" id="unique_3__unique_3_Connect_42_title_axh_rzg_wsb" nd:nd-id="title_axh_rzg_wsb"><span class="- topic/ph topic/title-wrapper ph title-wrapper">Reference</span></h1>
    
    <div class="- topic/body reference/refbody body refbody"><p class="- topic/shortdesc shortdesc" id="unique_3_Connect_42_shortdesc_am1_4zg_wsb" nd:nd-id="shortdesc_am1_4zg_wsb"></p>
        <table class="- topic/table table frame-all" colsep="1" frame="all" id="unique_3_Connect_42_table_wbf_rvz_vsb" nd:nd-id="table_wbf_rvz_vsb" rowsep="1" data-cols="8"><caption class="- topic/title title tablecap" data-caption-side="top" data-is-repeated="true"><span class="table--title-label">Table<span class="table--title-label-number"> 1</span><span class="table--title-label-punctuation">. </span></span><span class="table--title" id="unique_3_Connect_42_title_dmw_qzg_wsb" nd:nd-id="title_dmw_qzg_wsb"><span class="- topic/ph topic/title-wrapper ph title-wrapper">My table</span></span></caption><colgroup><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col><col style="width:12.5%"></col></colgroup><thead class="- topic/thead thead">
                    <tr class="- topic/row row">
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/entry entry colsep-1 rowsep-1" colname="col1" dita-ot:x="1" dita-ot:y="1" id="unique_3__unique_3_Connect_42_table_wbf_rvz_vsb__entry__1"></th>
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/entry entry colsep-1 rowsep-1" colname="col2" dita-ot:x="2" dita-ot:y="1" id="unique_3__unique_3_Connect_42_table_wbf_rvz_vsb__entry__2"></th>
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/entry entry colsep-1 rowsep-1" colname="col3" dita-ot:morecols="1" dita-ot:x="3" dita-ot:y="1" nameend="col4" namest="col3" colspan="2" id="unique_3__unique_3_Connect_42_table_wbf_rvz_vsb__entry__3"></th>
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/entry entry colsep-1 rowsep-1" colname="col5" dita-ot:x="5" dita-ot:y="1" id="unique_3__unique_3_Connect_42_table_wbf_rvz_vsb__entry__4"></th>
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/entry entry colsep-1 rowsep-1" colname="col6" dita-ot:x="6" dita-ot:y="1" id="unique_3__unique_3_Connect_42_table_wbf_rvz_vsb__entry__5"></th>
                        <th xmlns:dita-ot="http://dita-ot.sourceforge.net/ns/201007/dita-ot" class="- topic/en